// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hxrppmdwujlfpkcfumpm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4cnBwbWR3dWpsZnBrY2Z1bXBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNzE1ODQsImV4cCI6MjA3MDY0NzU4NH0.7bYq224VknRQM9j65ym3M95LpxKR144oxB3H1Axbxz4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});